name: Continuous Integration Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    name: Unit tests and code checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install CI
      run: |
          pip install "tox>=4.0"
          tox
        # python -m pip install --upgrade pip
        # pip install -r requirements.txt
    # - name: Run Tests
    #   run: |
    #     python manage.py test
